export type MasterDirectoryRow = {
  name: string;
  address: string;
  area: string;
  subtype: string;
  priority: string;
  sourceUrl: string;
  category: "culture" | "cafe" | "food";
};

export const masterDirectoryRows: MasterDirectoryRow[] = [
  { name: "D&DEPARTMENT JEJU 식음공간", address: "제주특별자치도 제주시 탑동로2길 3", area: "칠성로·탑동", subtype: "복합문화공간·식음", priority: "추천", sourceUrl: "https://www.d-department.com/", category: "food" },
  { name: "THE BARN BERLIN JEJU", address: "제주특별자치도 제주시 산지로 37-2 1층", area: "산지천·탐라문화광장·서부두", subtype: "카페", priority: "추천", sourceUrl: "https://www.instagram.com/thebarnberlin.korea/", category: "cafe" },
  { name: "갤러리 레미콘 산지천", address: "제주특별자치도 제주시 산지로 31", area: "산지천·탐라문화광장·서부두", subtype: "민간 갤러리", priority: "추천", sourceUrl: "https://www.instagram.com/galleryremicon/", category: "culture" },
  { name: "갤러리 숨비마루", address: "제주특별자치도 제주시 중앙로 지하 60 중앙지하상가 8번 출입구 인근", area: "중앙로 남측", subtype: "생활밀착형 갤러리", priority: "참고", sourceUrl: "https://www.yna.co.kr/view/AKR20250609060800056", category: "culture" },
  { name: "고씨주택·제주여행자센터", address: "제주특별자치도 제주시 관덕로17길 27-1", area: "관덕로·목관아", subtype: "도시재생 거점", priority: "참고", sourceUrl: "https://visitjeju.net/kr/festival/view?contentsid=CNTS_300000000014329", category: "culture" },
  { name: "고요산책", address: "제주특별자치도 제주시 중앙로12길 5 1층", area: "중앙로 남측", subtype: "북라운지·워케이션 공간", priority: "추천", sourceUrl: "https://www.instagram.com/goyowalk_jeju/", category: "culture" },
  { name: "곤밥2", address: "제주특별자치도 제주시 서부두남길 일대", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "검토", sourceUrl: "https://www.bizno.net/article/7061702201", category: "food" },
  { name: "김만덕기념관", address: "제주특별자치도 제주시 산지로 7", area: "산지천·탐라문화광장·서부두", subtype: "박물관", priority: "참고", sourceUrl: "https://www.mandukmuseum.or.kr/", category: "culture" },
  { name: "김영수도서관", address: "제주특별자치도 제주시 중앙로8길 18", area: "중앙로 남측", subtype: "도서관·지역공간", priority: "참고", sourceUrl: "https://www.visitjeju.net/korean/Bd/view.php?bno=1716&btable=report_info", category: "culture" },
  { name: "나이롱책방", address: "제주특별자치도 제주시 관덕로8길 17 2층", area: "관덕로·목관아", subtype: "독립서점·독서문화공간", priority: "추천", sourceUrl: "https://www.instagram.com/nylong.bookshop/", category: "culture" },
  { name: "내음커피바", address: "제주특별자치도 제주시 산지로 17 나동 1층", area: "산지천·탐라문화광장·서부두", subtype: "브루잉카페·독립잡지 연계공간", priority: "추천", sourceUrl: "https://www.instagram.com/naeeum_coffeebar/", category: "cafe" },
  { name: "노위스키", address: "제주특별자치도 제주시 중앙로 27-41 2층", area: "칠성로·탑동", subtype: "카페&바·LP·전시·공연", priority: "추천", sourceUrl: "https://www.instagram.com/nowhisky.jeju/", category: "cafe" },
  { name: "다금바리스타 산지천", address: "제주특별자치도 제주시 중앙로7길 31 2층", area: "산지천·탐라문화광장·서부두", subtype: "카페·바", priority: "추천", sourceUrl: "https://www.instagram.com/dagumbaristar/", category: "cafe" },
  { name: "다이노바이트샌드위치", address: "제주특별자치도 제주시 관덕로 16", area: "관덕로·목관아", subtype: "음식점", priority: "참고", sourceUrl: "https://m.visitjeju.net/kr/detail/view?contentsid=CNTS_000000000022185", category: "food" },
  { name: "돌담갤러리", address: "제주특별자치도 제주시 중앙로 58 Place1빌딩 지하 1층", area: "중앙로 남측", subtype: "소규모 갤러리", priority: "참고", sourceUrl: "https://www.instagram.com/doldam_gallery/", category: "culture" },
  { name: "동문시장 국수골목·먹거리점포", address: "제주특별자치도 제주시 관덕로14길 20 일대", area: "동문시장·동문로", subtype: "음식점", priority: "참고", sourceUrl: "https://m.visitjeju.net/kr/themtour/view?contentsid=CNTS_200000000012174", category: "food" },
  { name: "동진식당", address: "제주특별자치도 제주시 동문로4길 9", area: "동문시장·동문로", subtype: "음식점", priority: "참고", sourceUrl: "https://m.visitjeju.net/kr/themtour/view?contentsid=CNTS_300000000013849", category: "food" },
  { name: "또제 동문시장 본점", address: "제주특별자치도 제주시 동문로2길 27-3", area: "동문시장·동문로", subtype: "베이커리카페", priority: "참고", sourceUrl: "https://www.instagram.com/ddef_jeju/", category: "cafe" },
  { name: "리듬앤브루스", address: "제주특별자치도 제주시 무근성7길 11", area: "관덕로·목관아", subtype: "전시·카페 복합공간", priority: "추천", sourceUrl: "https://www.instagram.com/rhythm_and_brew_s/", category: "cafe" },
  { name: "마음에온[溫]", address: "제주특별자치도 제주시 칠성로길 29-1 1층", area: "칠성로·탑동", subtype: "한옥카페·전통차", priority: "추천", sourceUrl: "https://www.instagram.com/oncafe0707/", category: "cafe" },
  { name: "마일스 탑동점", address: "제주특별자치도 제주시 탑동로2길 3 1층", area: "칠성로·탑동", subtype: "재즈카페&바", priority: "추천", sourceUrl: "https://www.instagram.com/miles_lounge/", category: "cafe" },
  { name: "만첩", address: "제주특별자치도 제주시 관덕로3길 9-1 3층", area: "관덕로·목관아", subtype: "카페", priority: "참고", sourceUrl: "https://www.visitjeju.net/kr/detail/view?contentsid=CNTS_300000000013618", category: "cafe" },
  { name: "먼슬리 제주", address: "제주특별자치도 제주시 관덕로 40 1층", area: "관덕로·목관아", subtype: "카페&바(복합문화공간 겸)", priority: "추천", sourceUrl: "https://www.instagram.com/monthly_jeju_/", category: "cafe" },
  { name: "무슈부부커피스탠드", address: "제주특별자치도 제주시 관덕로 22 1층", area: "관덕로·목관아", subtype: "카페", priority: "참고", sourceUrl: "https://www.visitjeju.net/kr/themtour/view?contentsid=CNTS_300000000013077", category: "cafe" },
  { name: "무화과한입", address: "제주특별자치도 제주시 서부두남길 9-1", area: "산지천·탐라문화광장·서부두", subtype: "북카페·독립서점", priority: "추천", sourceUrl: "https://www.instagram.com/muhwagwa_1/", category: "cafe" },
  { name: "물항식당 탑동점", address: "제주특별자치도 제주시 임항로 일대", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "검토", sourceUrl: "https://map.kakao.com/?q=%EB%AC%BC%ED%95%AD%EC%8B%9D%EB%8B%B9%20%ED%83%91%EB%8F%99%EC%A0%90", category: "food" },
  { name: "배가본드", address: "제주특별자치도 제주시 관덕로15길 9 1층", area: "칠성로·탑동", subtype: "주류·안주 중심 요리주점", priority: "참고", sourceUrl: "https://www.instagram.com/vagabond.jeju/", category: "food" },
  { name: "부가네얼큰이 본점", address: "제주특별자치도 제주시 관덕로 15", area: "관덕로·목관아", subtype: "음식점", priority: "참고", sourceUrl: "https://www.visitjeju.net/kr/detail/view?contentsid=CNTS_300000000014236", category: "food" },
  { name: "비아아트·대동호텔 아트센터", address: "제주특별자치도 제주시 관덕로15길 6", area: "산지천·탐라문화광장·서부두", subtype: "민간 갤러리", priority: "추천", sourceUrl: "https://www.viaartjeju.com/", category: "culture" },
  { name: "사진예술공간 큰바다영", address: "제주특별자치도 제주시 만덕로 11 2층", area: "산지천·탐라문화광장·서부두", subtype: "사진 전문 전시공간", priority: "추천", sourceUrl: "https://www.instagram.com/yeomin.photo/", category: "culture" },
  { name: "산도롱앤드또똣", address: "제주특별자치도 제주시 중앙로 지하 60 지하1층 25호", area: "칠성로·탑동", subtype: "음식점", priority: "참고", sourceUrl: "https://m.visitjeju.net/kr/themtour/view?contentsid=CNTS_300000000013849", category: "food" },
  { name: "산지나미", address: "제주특별자치도 제주시 산지로 17 1층", area: "산지천·탐라문화광장·서부두", subtype: "주류·안주 중심 주점", priority: "참고", sourceUrl: "https://www.instagram.com/explore/search/keyword/?q=%EC%82%B0%EC%A7%80%EB%82%98%EB%AF%B8", category: "food" },
  { name: "산지천갤러리", address: "제주특별자치도 제주시 중앙로3길 36", area: "산지천·탐라문화광장·서부두", subtype: "전시공간", priority: "추천", sourceUrl: "https://www.instagram.com/sjcgallery/", category: "culture" },
  { name: "산지키친", address: "제주특별자치도 제주시 산지로 5-3 1층", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "추천", sourceUrl: "https://www.instagram.com/explore/search/keyword/?q=%EC%82%B0%EC%A7%80%ED%82%A4%EC%B9%9C", category: "food" },
  { name: "산지해장국", address: "제주특별자치도 제주시 임항로 34", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "참고", sourceUrl: "https://www.korearank.com/tour/tour_detail.php?uid=61131", category: "food" },
  { name: "삼도해장국", address: "제주특별자치도 제주시 중앙로14길 34", area: "중앙로 남측", subtype: "음식점", priority: "참고", sourceUrl: "https://visitjeju.net/kr/detail/view?contentsid=CNTS_300000000014525", category: "food" },
  { name: "서쪽부엌 서부두점", address: "제주특별자치도 제주시 서부두길 26", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "참고", sourceUrl: "https://www.instagram.com/jeju_westkitchen/", category: "food" },
  { name: "소설과 농담", address: "제주특별자치도 제주시 남성로 160", area: "삼도동", subtype: "북카페·편집숍", priority: "추천", sourceUrl: "https://www.instagram.com/novel.and.joke/", category: "cafe" },
  { name: "순아커피", address: "제주특별자치도 제주시 관덕로 32-1", area: "관덕로·목관아", subtype: "구옥카페", priority: "검토", sourceUrl: "https://www.tripinfo.co.kr/info.html?content_id=2840505&content_type_id=39", category: "cafe" },
  { name: "스튜디오126", address: "제주특별자치도 제주시 북성로 27 2층", area: "관덕로·목관아", subtype: "독립 전시공간", priority: "추천", sourceUrl: "https://www.instagram.com/studio126_jeju/", category: "culture" },
  { name: "아라리오뮤지엄 동문모텔 I", address: "제주특별자치도 제주시 산지로 37-5", area: "산지천·탐라문화광장·서부두", subtype: "미술관", priority: "추천", sourceUrl: "https://www.arariomuseum.org/m/page/VISITINGINFO_LOCATION_J.php", category: "culture" },
  { name: "아라리오뮤지엄 동문모텔 II", address: "제주특별자치도 제주시 산지로 23", area: "산지천·탐라문화광장·서부두", subtype: "미술관", priority: "추천", sourceUrl: "https://www.arariomuseum.org/m/page/VISITINGINFO_LOCATION_J.php", category: "culture" },
  { name: "아라리오뮤지엄 탑동시네마", address: "제주특별자치도 제주시 탑동로 14", area: "칠성로·탑동", subtype: "미술관", priority: "추천", sourceUrl: "https://www.arariomuseum.org/m/page/VISITINGINFO_HOURS.php", category: "culture" },
  { name: "아르코공연연습센터@제주", address: "제주특별자치도 제주시 중앙로14길 18 제주아트플랫폼 3~4층", area: "관덕로·목관아", subtype: "공연예술 연습공간", priority: "검토", sourceUrl: "https://www.arko.or.kr/pspace/", category: "culture" },
  { name: "아베베베이커리 제주", address: "제주특별자치도 제주시 동문로6길 4", area: "동문시장·동문로", subtype: "카페", priority: "참고", sourceUrl: "https://map.kakao.com/?q=%EC%95%84%EB%B2%A0%EB%B2%A0%EB%B2%A0%EC%9D%B4%EC%BB%A4%EB%A6%AC%20%EC%A0%9C%EC%A3%BC", category: "cafe" },
  { name: "아일랜드팩토리 풍류", address: "제주특별자치도 제주시 관덕로8길 31", area: "관덕로·목관아", subtype: "문화공간형 로스터리카페·빈티지숍", priority: "추천", sourceUrl: "https://jejuyouth.com/m/pages.php?p=3_2_1_1&sca=%EB%B3%B5%ED%95%A9%EB%AC%B8%ED%99%94%EA%B3%B5%EA%B0%84", category: "cafe" },
  { name: "아트스페이스 빈공간", address: "제주특별자치도 제주시 관덕로3길 15 1층", area: "관덕로·목관아", subtype: "독립 복합문화공간", priority: "추천", sourceUrl: "https://www.instagram.com/biniartspace/", category: "culture" },
  { name: "아트스페이스·씨", address: "제주특별자치도 제주시 중앙로 69 3층·지하 1층", area: "중앙로 남측", subtype: "독립 복합문화공간", priority: "참고", sourceUrl: "https://artspacec.com/", category: "culture" },
  { name: "어반브루잉", address: "제주특별자치도 제주시 관덕로 16-1 1층", area: "관덕로·목관아", subtype: "로스터리카페", priority: "추천", sourceUrl: "https://www.instagram.com/urbanbrewing.official/", category: "cafe" },
  { name: "연호제 구내식당", address: "제주특별자치도 제주시 산지로 5 1층", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "추천", sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=714f2f76-5147-48c6-af57-cf5ba3d187e1", category: "food" },
  { name: "예술공간 이아", address: "제주특별자치도 제주시 중앙로14길 21", area: "관덕로·목관아", subtype: "복합문화공간", priority: "추천", sourceUrl: "https://www.instagram.com/artspaceiaa/", category: "culture" },
  { name: "오랑우탄면사무소 제주공항점", address: "제주특별자치도 제주시 관덕로6길 12", area: "관덕로·목관아", subtype: "음식점", priority: "추천", sourceUrl: "https://www.instagram.com/orangutan_noodle_office/", category: "food" },
  { name: "온차", address: "제주특별자치도 제주시 서부두남길 12", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "참고", sourceUrl: "https://m.tripinfo.co.kr/info.html?content_id=2857388&content_type_id=39", category: "food" },
  { name: "우무 동문시장점", address: "제주특별자치도 제주시 관덕로8길 40-1", area: "동문시장·동문로", subtype: "카페", priority: "참고", sourceUrl: "https://www.visitjeju.net/kr/detail/view?contentsid=CNTS_200000000008492", category: "cafe" },
  { name: "우진해장국", address: "제주특별자치도 제주시 서사로 11", area: "삼도동", subtype: "음식점", priority: "참고", sourceUrl: "https://triple.guide/restaurants/4c9abaef-0a7e-4b93-95d5-a209e96e8b69", category: "food" },
  { name: "웰컴버거", address: "제주특별자치도 제주시 중앙로7길 31 1층", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "추천", sourceUrl: "https://www.instagram.com/welcomeburger_jeju/", category: "food" },
  { name: "윤재커피", address: "제주특별자치도 제주시 중앙로12길 1", area: "중앙로 남측", subtype: "카페", priority: "참고", sourceUrl: "https://m.visitjeju.net/kr/themtour/view?contentsid=CNTS_300000000013185", category: "cafe" },
  { name: "음파", address: "제주특별자치도 제주시 독짓골2길 17 102호", area: "삼도동", subtype: "LP·브런치카페", priority: "추천", sourceUrl: "https://www.instagram.com/ummpah_/", category: "cafe" },
  { name: "이돈갓", address: "제주특별자치도 제주시 칠성로길 27 2층", area: "칠성로·탑동", subtype: "음식점", priority: "참고", sourceUrl: "https://m.tripinfo.co.kr/info.html?content_id=2861702&content_type_id=39", category: "food" },
  { name: "자양식당", address: "제주특별자치도 제주시 관덕로6길 17 1층", area: "관덕로·목관아", subtype: "음식점", priority: "추천", sourceUrl: "https://triple.guide/restaurants/5a0f8bf6-71a7-472a-81b1-eef6d4297503", category: "food" },
  { name: "자연몸국", address: "제주특별자치도 제주시 중앙로7길 19", area: "동문시장·동문로", subtype: "음식점", priority: "참고", sourceUrl: "https://www.tripinfo.co.kr/info.html?content_id=2840668&content_type_id=39", category: "food" },
  { name: "적점", address: "제주특별자치도 제주시 산지로 17 나동 1층", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "추천", sourceUrl: "https://www.instagram.com/jeokjeom_jeju/", category: "food" },
  { name: "제주고로 산지", address: "제주특별자치도 제주시 산지로 5-3 1층", area: "산지천·탐라문화광장·서부두", subtype: "음식점", priority: "추천", sourceUrl: "https://www.instagram.com/jejugoro_sanji/", category: "food" },
  { name: "제주바솔트", address: "제주특별자치도 제주시 중앙로13길 6 1층", area: "동문시장·동문로", subtype: "제주 디저트카페", priority: "참고", sourceUrl: "https://www.instagram.com/jejubasalt/", category: "cafe" },
  { name: "제주시소통협력센터", address: "제주특별자치도 제주시 관덕로 44", area: "관덕로·목관아", subtype: "커뮤니티·행사공간", priority: "참고", sourceUrl: "https://www.jejusotong.kr/", category: "culture" },
  { name: "제주아트플랫폼", address: "제주특별자치도 제주시 중앙로14길 18", area: "관덕로·목관아", subtype: "공연·복합문화공간", priority: "추천", sourceUrl: "https://www.jfac.kr/", category: "culture" },
  { name: "제주트립티 산지", address: "제주특별자치도 제주시 관덕로17길 29", area: "산지천·탐라문화광장·서부두", subtype: "카페", priority: "참고", sourceUrl: "https://www.instagram.com/tripticoffee/", category: "cafe" },
  { name: "제주해변공연장", address: "제주특별자치도 제주시 중앙로 2", area: "칠성로·탑동", subtype: "야외 공연장", priority: "참고", sourceUrl: "https://www.jeju.go.kr/jejuculture/", category: "culture" },
  { name: "젤라떼리아 브라보", address: "제주특별자치도 제주시 산지로 19 1층", area: "산지천·탐라문화광장·서부두", subtype: "디저트·젤라또", priority: "추천", sourceUrl: "https://www.instagram.com/bravo.gelato/", category: "cafe" },
  { name: "종이잡지클럽 제주", address: "제주특별자치도 제주시 산지로 17 나동 2층", area: "산지천·탐라문화광장·서부두", subtype: "독립출판·문화공간", priority: "추천", sourceUrl: "https://kr.trip.com/moments/theme/poi-sanjicheon-142391722-restaurant-993134/", category: "culture" },
  { name: "진아떡집", address: "제주특별자치도 제주시 동문로4길 7-1", area: "동문시장·동문로", subtype: "떡·간식", priority: "추천", sourceUrl: "https://www.ok114.co.kr/0647570229", category: "food" },
  { name: "첨목", address: "제주특별자치도 제주시 산지로 25 1층", area: "산지천·탐라문화광장·서부두", subtype: "음식점·목로주점", priority: "추천", sourceUrl: "https://www.instagram.com/additional_point/", category: "food" },
  { name: "칠성뷔페", address: "제주특별자치도 제주시 관덕로11길 17 4층", area: "칠성로·탑동", subtype: "음식점", priority: "검토", sourceUrl: "https://pf.kakao.com/_xkPsPC", category: "food" },
  { name: "카페단단", address: "제주특별자치도 제주시 관덕로4길 1-6 1층", area: "관덕로·목관아", subtype: "카페", priority: "추천", sourceUrl: "https://www.instagram.com/cafedandan/", category: "cafe" },
  { name: "카페삼도동", address: "제주특별자치도 제주시 관덕로4길 14-1 1층", area: "관덕로·목관아", subtype: "카페", priority: "참고", sourceUrl: "https://www.instagram.com/cafe.samdodong/", category: "cafe" },
  { name: "카페성지 성지점", address: "제주특별자치도 제주시 성지로 10 1층", area: "이도동", subtype: "핸드드립카페", priority: "추천", sourceUrl: "https://www.instagram.com/cafeseongji/", category: "cafe" },
  { name: "컴플렉스커피", address: "제주특별자치도 제주시 중앙로14길 4", area: "중앙로 남측", subtype: "로스터리카페", priority: "참고", sourceUrl: "https://www.instagram.com/complex_coffeelab/", category: "cafe" },
  { name: "키미디", address: "제주특별자치도 제주시 관덕로8길 38 1~3층", area: "관덕로·목관아", subtype: "디저트카페·라이프스타일 팝업", priority: "추천", sourceUrl: "https://www.instagram.com/kimidi_jeju/", category: "cafe" },
  { name: "키에키 로스팅 룸", address: "제주특별자치도 제주시 중앙로 88-1 1층", area: "중앙로 남측", subtype: "로스터리카페", priority: "추천", sourceUrl: "https://www.instagram.com/kiekee.roasting.room/", category: "cafe" },
  { name: "탑동스페이스원", address: "제주특별자치도 제주시 탑동로2길 7 1층", area: "칠성로·탑동", subtype: "팝업·전시공간", priority: "참고", sourceUrl: "https://www.instagram.com/explore/tags/spaceonejeju/", category: "culture" },
  { name: "탑부평 본점", address: "제주특별자치도 제주시 관덕로15길 26", area: "칠성로·탑동", subtype: "음식점", priority: "참고", sourceUrl: "https://www.instagram.com/explore/search/keyword/?q=%ED%83%91%EB%B6%80%ED%8F%89", category: "food" },
  { name: "토닥토닥", address: "제주특별자치도 제주시 관덕로15길 7 2층", area: "칠성로·탑동", subtype: "음식점", priority: "참고", sourceUrl: "https://m.visitjeju.net/kr/themtour/view?contentsid=CNTS_300000000013849", category: "food" },
  { name: "팔즈", address: "제주특별자치도 제주시 중앙로8길 11 1층", area: "중앙로 남측", subtype: "스페셜티카페", priority: "추천", sourceUrl: "https://www.instagram.com/pals.coffeekr/", category: "cafe" },
  { name: "펍65", address: "제주특별자치도 제주시 산지로 17 가동 2층", area: "산지천·탐라문화광장·서부두", subtype: "주류·안주 중심 라이브펍", priority: "추천", sourceUrl: "https://www.instagram.com/pub65_jeju_crew/", category: "food" },
  { name: "푸아루", address: "제주특별자치도 제주시 남성로23길 9 1층", area: "삼도동", subtype: "디저트·필터커피", priority: "추천", sourceUrl: "https://www.instagram.com/puaru.jeju/", category: "cafe" },
  { name: "픽업카페 제주본점", address: "제주특별자치도 제주시 남성로 167", area: "중앙로 남측", subtype: "베이커리카페", priority: "참고", sourceUrl: "https://www.instagram.com/____pickup/", category: "cafe" },
  { name: "하토말차", address: "제주특별자치도 제주시 남성로 167 2층", area: "삼도동", subtype: "카페·티하우스", priority: "추천", sourceUrl: "https://www.instagram.com/hato_jeju/", category: "cafe" },
  { name: "한일동문식당", address: "제주특별자치도 제주시 동문로 6-4 1층", area: "동문시장·동문로", subtype: "음식점", priority: "참고", sourceUrl: "https://m.visitjeju.net/kr/themtour/view?contentsid=CNTS_300000000013849", category: "food" },
];

